

prometheus:
  alertmanager:
    image:
      repository: prom/alertmanager
  configmapReload:
    prometheus:
      image:
        repository: jimmidyson/configmap-reload
    alertmanager:
      image:
        repository: jimmidyson/configmap-reload
  initChownData:
    image:
      repository: busybox
  nodeExporter:
    image:
      repository: prom/node-exporter
  pushgateway:
    image:
      repository: prom/pushgateway
  server:
    image:
      repository: prom/prometheus

  serverFiles:
    alerting_rules.yml: 
      groups:
        - name: frontend
          rules:
          - alert: High_CPU_Usage
            expr: sum (rate (container_cpu_usage_seconds_total{pod=~"^client.*$"}[2m])) / sum (machine_cpu_cores) > 0.1
            labels:
              team: frontend
              severity: critical
            annotations:
              summary: "CPU 占用高"
              description: "client 服务的 CPU 使用达到了惊人的 {{ $value }}"

  alertmanagerFiles:
    alertmanager.yml:
      global: {}
      receivers:
        - name: default-receiver
        - name: gitter_message
          webhook_configs:
            - url: 'http://gitter-messager'
      route:
        group_wait: 10s
        group_interval: 5m
        receiver: default-receiver
        repeat_interval: 3h
        routes: 
          - receiver: gitter_message
            match:
              team: frontend

grafana:
  image:
    repository: grafana/grafana
  initChownData:
    image:
      repository: busybox
  downloadDashboardsImage:
    repository: curlimages/curl

