apiVersion: v1
kind: Pod
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  initContainers:
    - name: git
      image: alpine/git:v2.24.1
      workingDir: /website
      command: ["git"]
      args: ["clone", "--single-branch", "--branch", "master", "https://gitee.com/idcf-devops-on-kubernetes/static-site.git", "."]
      volumeMounts:
        - name: website
          mountPath: /website
  containers:
    - name: nginx
      image: nginx:1.17.9-alpine
      command: ["/bin/sh"]
      args: ["-c", "sed -i 's:location / {:absolute_redirect off;\\nlocation / {:' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
      ports:
        - name: http
          containerPort: 80
      resources:
        limits:
          cpu: 200m
          memory: "256Mi"
      volumeMounts:
        - name: website
          mountPath: /usr/share/nginx/html
  volumes:
    - name: website
      emptyDir: {}
